edgexfoundry/device-mqtt-go

internal/driver/driver.go
internal/driver/driver_test.go
internal/driver/incominglistener.go
internal/driver/responselistener.go

 Check incoming data's field and check value type appropriate when convert reading data

---

internal/driver/driver.go
internal/driver/driver_test.go

Fix receipt of non-float number data will cause a panic in newResult function

---

internal/driver/driver.go
internal/driver/readinghandler.go

Refactor handleReadingStringValue method

---

internal/driver/incominglistener.go
internal/driver/responselistener.go

Check connection status before close it

---

internal/driver/driver.go
internal/driver/readingchecker.go

Refactor checkValueInRange method

---

cmd/res/configuration.toml
cmd/res/docker/configuration.toml
go.mod

This PR resolves github issue #31

Update device SDK and toml files

---

cmd/res/example/configuration.toml
go.mod
internal/driver/config.go
internal/driver/config_test.go
internal/driver/driver.go
internal/driver/protocolpropertykey.go

Fix #33 
Updated to the replacement of Device.Addressable with Device Protocols, and the deprecation of Schedule* objects by device-sdk-go.
Signed-off-by: Bruce <weichou1229@gmail.com>

Updated to the replacement of Device.Addressable with Device Protocols

---

internal/driver/driver.go

Fix #30 
```
defer client.Disconnect(5000)
```
This code snippet will cause panic when the connection already fails to establish.
Therefore, check connection status before close it.

Optimize error message and check connection status when close the MQTT connection

---

go.mod
internal/driver/driver.go
internal/driver/driver_test.go

Change import package name logging to logger

---

cmd/res/example/configuration.toml
cmd/res/example/mqtt.test.device.profile.yml
go.mod

Update device-sdk-go and add AutoEvents to example

---

Makefile

Remove make prepare target from the Makefile

---

cmd/res/example/configuration.toml
cmd/res/example/mqtt.test.device.profile.yml
mock/device.go

Add eNotation and Base64 to device profile example for float encoding

---

go.mod

Upgrade the lib to use the latest device-sdk and core-contract
Fix #57

Upgrade to latest device-sdk and core-contract

---

internal/driver/driver.go
internal/driver/responselistener.go

User sync map instead of the general map
Fix #70

Fix the thread safe issue in response map

---

internal/driver/driver.go
internal/driver/responselistener.go

User sync map instead of the general map
Fix #70

[edingurgh] Fix the thread safe issue in response map

---

snap/snapcraft.yaml

Specify consul address in registry arg in snap (master)

---

.gitignore
Makefile

Signed-off-by: Tyler Powers <tyler.m.powers@intel.com>

Add code coverage output file

---

cmd/res/example/configuration-autoevents.toml
cmd/res/example/configuration.toml

Duplicate of #94, but for Edinburgh

Remove AutoEvents from default example config, create new config for AutoEvents (edinburgh)

---

cmd/res/example/mqtt.test.device.profile.yml

Replace the http status code 503 with 500 in example profile

---

cmd/res/example/mqtt.test.device.profile.yml

Modify the exception code description of example profile

---

Dockerfile

Fix #101
Add flag "--registry=consul://edgex-core-consul:8500" to the Dockerfile ENTRYPOINT.

Use registry running in docker

---

cmd/res/configuration.toml
cmd/res/docker/configuration.toml

Fix #103 
Set up the default ProfilesDir path to ./res

Set up the default ProfilesDir path to ./res

---

go.mod
internal/driver/driver.go

Fix #108 
Update to the Latest Version of device-sdk-go and go-mod-core-contracts.

Update Device Service to Latest Version of Device SDK

---

cmd/res/example/mqtt.test.device.profile.yml
go.mod

Update go.mod: Update device SDK to the latest version
Update device profile:
- Replace "object" with "deviceResource"
- Remove "parameter" fields from get commands
Fix #110

Update sdk version and device profile.

---

go.mod

Update the SDK according to the async issue
Fix #112

Update sdk to the latest version.

---

Attribution.txt
Makefile
bin/test-attribution-txt.sh
bin/test-go-mod-tidy.sh

Signed-off-by: Iain Anderson <iain@iotechsys.com>

Add Attribution file and extend maketest to check it (#118)

---

cmd/res/configuration.toml
cmd/res/example/configuration-autoevents.toml
cmd/res/example/configuration.toml
go.mod

fix #154
fix #155
upgrade SDK to v1.2.3, remove ClientMonitor field and
add ServerBindAddr field in configuration.toml
Signed-off-by: Chris Hung <chris@iotechsys.com>

Upgrade SDK version and configuration file

---

Dockerfile

Signed-off-by: Koppolu <venkata.subbareddy.koppolu@intel.com>
Issue Number:
https://github.com/edgexfoundry/device-mqtt-go/issues/164

refactor: update dockerfile to appropriately use ENTRYPOINT and CMD, closes#164

---

cmd/res/configuration.toml
cmd/res/example/configuration-autoevents.toml
cmd/res/example/configuration.toml

Support logging has been removed so now the configuration is obsolete.
Issue Number: #194 
Removed the following sections from configuration.toml:
- [Logging]
- [Clients.Logging]
fix: #194

feat: Remove Logging configuration

---

Dockerfile
Dockerfile.build
go.mod
snap/snapcraft.yaml

- [NA] Tests for the changes have been added (for bug fixes / features)
- [NA] Docs have been added / updated (for bug fixes / features)
This PR updates the service to use go 1.16 (including the snap build), and also fixes a snap build breakage caused by recent build changes.
- [ x] No

fix(build): update to go 1.16

---

Makefile
cmd/res/configuration.toml
go.mod
internal/driver/config.go

no secure MessageBus capability
Secure MessageBus capability added

feat: Add secure MessagBus capability

---

cmd/res/devices/mqtt.test.device-autoevents.toml

Signed-off-by: Chris Hung <chris@iotechsys.com>

refactor: rename example device AutoEvent Fequency to Interval 

---

snap/hooks/install
snap/hooks/pre-refresh
snap/snapcraft.yaml

- fix destination paths for /profiles and /devices
- bump epoch to 2
- set release name to 'ireland'
- update snap versioning to use git revision rather than VERSION file
Signed-off-by: Siggi Skulason <siggi.skulason@canonical.com>
The snap doesn't build
The snap builds correctly.

fix(snap): fix v2 update issues

---

cmd/res/configuration.toml
internal/driver/config.go
internal/driver/driver.go

Close: #212
Extract the command response retry interval as the writable configuration

feat: Extract the command response retry interval as configuration

---

GOVERNANCE.md
OWNERS.md
cmd/res/configuration.toml
cmd/res/devices/mqtt.test.device.toml

also added governance.md and owner.md files for LF Edge
Signed-off-by: jpwhitemn <jpwhite_mn@yahoo.com>

fix: update all TOML to use quote and not single-quote

---

.github/PULL_REQUEST_TEMPLATE.md

PR Template doesn't have any verbiage about related Docs PR
PR Template has verbiage about related Docs PR

docs: Add required Docs PR verbiage to PR template

---

cmd/res/profiles/mqtt.test.device.profile.yml
internal/driver/driver.go
internal/driver/driver_test.go
internal/driver/readingchecker.go

- Update sample profile
- Handle Object value for read and write operation
Closes: #321
Signed-off-by: bruce <weichou1229@gmail.com>
[<link to docs PR>](https://github.com/edgexfoundry/edgex-docs/pull/635)
1. Run the device-mqtt-go with predefined device and profile
2. Test write and read cmd for object value type

feat: Add support for new Object reading type

---

snap/README.md

Signed-off-by: Mengyi <mengyi.wang@canonical.com>

docs(snap): remove two obsolete environment variables

---

Jenkinsfile

Tests are now done using Github Actions. See https://github.com/edgexfoundry/device-mqtt-go/pull/343
Signed-off-by: Farshid Tavakolizadeh <farshid.tavakolizadeh@canonical.com>

test(snap): disable snap build on jenkins

---

.golangci.yml
Makefile
internal/driver/driver.go
internal/driver/incominglistener.go
internal/driver/readingchecker.go
internal/driver/responselistener.go
mock/device.go

fixes: #352
Signed-off-by: jpwhitemn <jpwhite_mn@yahoo.com>

feat: enable gosec and default linter set

---

Dockerfile
Makefile
bin/test-attribution-txt.sh
go.mod
go.sum
mock/device.go
snap/local/helper-go/Makefile
snap/local/helper-go/go.mod
snap/snapcraft.yaml

Signed-off-by: Leonard Goodell <leonard.goodell@intel.com>
run `make build`
run `make test`
run `make docker`

build: Upgrade to Go 1.18, fix linter issues and optimize attribution script

---

.github/dependabot.yml

Signed-off-by: Farshid Tavakolizadeh <farshid.tavakolizadeh@canonical.com>

ci(snap): Add dependabot config for snap go mod

---

snap/local/helper-go/install.go

Signed-off-by: Mengyi Wang <mengyi.wang@canonical.com>

refactor(snap): Remove duplicate file copying in install hook

---

.github/dependabot.yml
go.mod
go.sum

Signed-off-by: Leonard Goodell <leonard.goodell@intel.com>

build: Update to use released SDK

---

cmd/res/configuration.toml
internal/driver/config.go
internal/driver/driver.go

BREAKING CHANGE: updated secret path to secretName
make test
make docker

refactor!: updated secret path to secretName

---

Dockerfile
Makefile
go.mod
snap/local/helper-go/go.mod
snap/snapcraft.yaml

verify make docker works
Run non-secure EdgeX stack with mqtt-broker
Build and run service from command line
Verify logs have no errors bootstrapping.

build: Update to Go 1.20, Alpine 3.17 and linter v1.51.2

---

internal/driver/driver.go

fix: update log to avoid leaking messageBus credentials

---

cmd/res/configuration.yaml
cmd/res/devices/mqtt.test.device.yaml
internal/driver/config.go
internal/driver/driver.go
internal/driver/incominglistener.go
internal/driver/responselistener.go

BREAKING CHANGE: Removed single level topics, multi level is used by default
closes: #551
https://github.com/edgexfoundry/edgex-docs/pull/1038
1. Start edgex with mqtt-broker
2. Ran multi-level simulator described in https://docs.edgexfoundry.org/3.0/examples/Ch-ExamplesAddingMQTTDevice/#creating-and-running-a-mqtt-device-simulator
3. Verify that device mqtt sucessfully published incoming messages  from simulator
4. Also ran `make test`

refactor!: Make multi-level topics the only implementation

---

README.md

docs: Update Readme to refer to 3.1 main doc page
