- cmd/res/example/mqtt.test.device.profile.yml
Remove RO 'property=value' from example device profile, because this attribute was removed from the model.
Fix #45
> Remove RO 'property=value' from example device profile

- .gitignore
- snap/hooks/configure
- snap/hooks/install
- snap/hooks/pre-refresh
- snap/snapcraft.yaml
Fixes #54
The CI jobs for the snap have been created in https://github.com/edgexfoundry/ci-management/pull/370, so this PR is ready to be reviewed.
To test this snap, on a linux machine (can be a virtual machine):
1. Install snapcraft and multipass with `snap install snapcraft --classic` and `snap install multipass --classic --beta`
2. Checkout this branch using git
3. Build the snap by going to the root directory of this project and running `snapcraft`.
4. The build should produce a .snap file named `edgex-device-mqtt*.snap`, install this snap with `snap install --dangerous edgex-device-mqtt*.snap`
Assuming all of the above works, the snap is installed and the things to check are:
Additionally, you should be able to test this by running a MQTT broker on your system and creating a device …
> Add initial snap packaging

- snap/snapcraft.yaml
As per edgexfoundry/device-sdk-go#274, the
registry arg for device services now needs a value, so use the default
value of consul from the edgexfoundry snap.
Fixes #75
> Specify consul address in registry arg in snap

- snap/hooks/install
- snap/snapcraft.yaml
Duplicate of #84 but for Edinburgh
Note that since this is just shipping additional files, we don't need to do a dot release here for the device service, it's just a packaging change.
> Install the example config file + device profile in the snap (edinburgh)

- snap/hooks/install
- snap/snapcraft.yaml
* Process the ProfilesDir properly so it's in $SNAP_DATA
* Copy the device profile in the install hook so it's available when the service starts running and is imported by default
Fixes #83 for master/fuji
> Install the example config file + device profile in the snap

- cmd/res/example/configuration-autoevents.toml
- cmd/res/example/configuration.toml
* Remove AutoEvents from the default configuration.toml in examples/
* Add new configuration-autoevents.toml for showing how AutoEvents works with the device service
* Rename the default device to `MQTT-test-device` w/o spaces so that it doesn't trigger awkward bugs with having spaces in URL request paths and parameters.
Fixes #87
> Remove AutoEvents from default example config, create new config for AutoEvents

- Dockerfile
Add license/copyright labels to the docker container.
Fix #127
> Add license/copyright labels to container

- Dockerfile
Add license/copyright labels to the docker container
Fix #127
> Fuji: Add license/copyright labels to container

- snap/snapcraft.yaml
Update the snap to the 1.1.1.
This has been tested against the latest stable version of the edgexfoundry snap (version: 1.1.0-20200213+5c8c3243, revision: 2049) on an Ubuntu Desktop system running 18.04 LTS.
> Fuji update snap to 1.1.1

- Jenkinsfile
- snap/snapcraft.yaml
add buildSnap:true option to enable snap builds in the Jenkins pipeline. This will replace the freestyle jjb jobs. Also had to update to Go 1.13 to fix the snap build. I matched the same version we are using for docker builds at the moment.
Signed-off-by: Ernesto Ojeda <ernesto.ojeda@intel.com>
> Add new buildSnap option to build snap in Jenkins pipeline

- snap/snapcraft.yaml
This change removes the build-time edit of the `configuration.toml` file and instead uses an
environment variable config override to update **Device.ProfilesDir**.
This resolves issue #149.
To test, install the main edgex snap, install the snap built from this PR, start a command to watch log output, and then start the service:
```
$ sudo snap install edgexfoundry
$ sudo snap install edgex-device-mqtt_*.snap --dangerous
$ sudo snap logs edgex-device-mqtt.device-mqtt -f | grep "Environment override"
```
**Note** -- the `--dangerous` flag is used to install an unsigned snap (i.e. a snap that's been built locally).
In another terminal run:
```$ sudo snap start edgex-device-mqtt.device-mqtt```
You should see the following log message output:
> 2020-06-04T14:46:19Z …
> snap: add env override for ProfilesDir

- Attribution.txt
- go.mod
- internal/driver/driver_test.go
- internal/driver/readingchecker.go
fix #143
Signed-off-by: weichou <weichou1229@gmail.com>
If the float value is zero, the device service will throw error "parse reading fail. Reading 0 is out of the value type(11)'s range"
Issue Number: #143 
Modify float value checking condition to make the zero value is valid
github.com/stretchr/testify v1.5.1
Import stretchr/testify v1.5.1 and dependency libs for writing tests.
This fix is can refer to edgexfoundry/device-sdk-go#358
> fix: Modify float value checking condition

- internal/driver/config.go
- internal/driver/driver.go
Fix #160
Signed-off-by: weichou <weichou1229@gmail.com>
Service will panic when the config is unable to load.
Issue Number: #160 
Return error instead of the panic if required config not found and modify the config username and pwd to optional field.
> fix: Return error instead of the panic if required config not found

- cmd/res/configuration.toml
closes 
Signed-off-by: lenny <leonard.goodell@intel.com>
missing Type='vault' from [SecretStore] config
Added Type='vault' to [SecretStore] config
> fix: Add Type='vault' to [SecretStore] config

- Dockerfile
- Makefile
- cmd/main.go
- cmd/res/configuration.toml
- go.mod
**Dependent on edgexfoundry/device-sdk-go#926**
Service key constants have the edgex- prefix
Service key constants no longer have the edgex- prefix
Hyphen in Overrides are converted to underscore
BREAKING CHANGE: Service key names used in configuration have changed.
> refactor: Update for new service key names and overrides for hyphen to underscore

- cmd/res/devices/mqtt.test.device-autoevents.toml
- cmd/res/devices/mqtt.test.device.toml
- cmd/res/profiles/mqtt.test.device.profile.yml
c## PR Checklist
Profile as invalid "." characters in the name
"."s in Profile name changed to "-"s
> fix: Change "."s in profile name to "-"s

- Attribution.txt
- README.md
- cmd/res/configuration.toml
- cmd/res/devices/mqtt.test.device.toml
- cmd/res/profiles/mqtt.test.device.profile.yml
- go.mod
- internal/driver/config.go
- internal/driver/driver.go
- internal/driver/incominglistener.go
- internal/driver/responselistener.go
Closes #282
Signed-off-by:Jennifer Williams <jennifer.m.williams@intel.com>
Signed-off-by:Elizabeth J Lee <elizabeth.j.lee@intel.com>
###Related Docs PR now required (if applicable)
Related Docs PR:
https://github.com/edgexfoundry/edgex-docs/pull/566
Currently the MQTT device uses a payload that includes metadata for the device as a single-level topic.
Issue #282
Adds optional configuration for multi-level topics, which removes the metadata from the payload to leave only the values.
Follow documentation to enable UseTopicLevels feature.
> feat: add UseMqttLevels capability to pass in metadata

- snap/snapcraft.yaml
The makefile requires a VERSION file to be present when building the device service.
This commit creates the file using the current git tag.
Signed-off-by: Siggi Skulason <siggi.skulason@canonical.com>
1. Build the snap and verify that you see a valid version in
```
GCO_ENABLED=1 GO111MODULE=on go build -ldflags "-X github.com/edgexfoundry/device-mqtt-go.Version=2.0.1-dev.10" -o cmd/device-mqtt ./cmd
```
2. Test the REST endpoint at `curl http://localhost:59880/api/v2/version`
> fix(snap): create VERSION file during snap build

- README.md
This PR adds a ~deployment~ packaging section to reference developer information about the docker and snap packaging.
The idea is to have a similar README section across all device/app service repos. 
In addition, it bumps the docs version to 2.1.
> docs: Add deployment section to readme

- snap/snapcraft.yaml
The metadata kept in snapcraft.yaml is obsolete because it is being overridden on the store. This change will allow sourcing the central copy of metadata.
See https://github.com/canonical/edgex-snap-metadata/issues/2
Signed-off-by: Farshid Tavakolizadeh <farshid.tavakolizadeh@canonical.com>
> build(snap): source metadata from repo

- cmd/res/configuration.toml
The `MQTTBrokerInfo` configuration section set the value of `Host` to `0.0.0.0`. There are two issues:
1. The whole configuration is about the MQTT Client, rather than the broker. Calling it broker and setting the host to `0.0.0.0` gives the false impression than this service is spinning up a broker with bind address set to `0.0.0.0` to listen on all interfaces.
2. IP address `0.0.0.0` is an invalid example for a client, because there can never be a broker at that address!
https://github.com/edgexfoundry/device-mqtt-go/blob/af7f42834155496da65d108934e36d5a2fb2bcc1/cmd/res/configuration.toml#L101-L130
I suggest changing `MQTTBrokerInfo` to `MQTTClient` in future. But in this PR, I simply change the Host to `localhost` to avoid confusion and make it a correct example.
Signed-off-by: Farshid …
> fix: replace broker host config value with a valid example

- snap/local/helper-go/configure.go
- snap/local/helper-go/install.go
- Use library function for autostart processing and config processing
- Replace deprecated hooks package with env package
Signed-off-by: Mengyi Wang <mengyi.wang@canonical.com>
1. Install and setup:
```
snap install edgex-device-mqtt_2.3.0-dev.13_amd64.snap --devmode
snap install edgexfoundry
snap connect edgexfoundry:edgex-secretstore-token edgex-device-mqtt:edgex-secretstore-token
```
2. Validate that autostart works as expected:
```
$ snap set edgex-device-mqtt autostart=true
$ snap services edgex-device-mqtt …
```
> build(snap): Upgrade install/configure hooks to use snap hook 2.4.1

- snap/snapcraft.yaml
Testing locally with [edgex-snap-testing suite](https://github.com/canonical/edgex-snap-testing/tree/main/test/suites/device-mqtt):
```
edgex-snap-testing$ LOCAL_SNAP=~/Desktop/edgex400/device-mqtt-go/edgex-device-mqtt_3.0.0-dev.23_amd64.snap go test -v ./test/suites/device-mqtt/
2023/04/24 11:35:06 [CLEAN]
2023/04/24 11:35:06 [exec] sudo snap remove --purge edgex-device-mqtt
[sudo] password for mengyi: 
2023/04/24 11:35:09 [stderr] snap "edgex-device-mqtt" is not installed
2023/04/24 11:35:09 [exec] sudo snap remove …
```
> build(snap): Upgrade snap base to core22

- cmd/res/configuration.yaml
- cmd/res/profiles/mqtt.test.device.profile.yml
- internal/driver/driver.go
- internal/driver/driver_test.go
- internal/driver/incominglistener.go
BREAKING CHANGE: The published async payload must now be json containing the resource names and values, even when a single resource is sent. Redendent single resource Device Commands (`testrandfloat32`, `testrandfloat64`, `testping` and `testmessage`) in `mqtt.test.device.profile.yml` have be removed. Use the corrisponding resource name (`randfloat32`, `randfloat64`, `ping` or `message`) instead.
closes https://github.com/edgexfoundry/device-mqtt-go/issues/299
https://github.com/edgexfoundry/edgex-docs/pull/1046
Run the updated example …
> feat!: Handle receiving multiple readings in the async payload

- go.mod
- go.sum
- internal/driver/incominglistener.go
fixes #603
run non-secure edgex with mqtt-broker
Use mqtt.FX to publish following data
- `1.06` to incoming/data/MQTT-test-device/randfloat32
- `6.78` to incoming/data/MQTT-test-device/randfloat64
- `pong` to incoming/data/MQTT-test-device/ping
- `Hi World` to incoming/data/MQTT-test-device/message
- `{}` to incoming/data/MQTT-test-device/json
- `{"randfloat32":0.8, "randfloat64": 1.2, "message": "hi" }` to incoming/data/MQTT-test-device/allValues
- `{"randfloat32":0.8}` to incoming/data/MQTT-test-device/randfloat32 …
> fix: [WIP BUG] Add back ability for async payload to just be value when for single resource
